POST http://localhost:3000/api/wilder
Content-Type: application/json

{
	"name": "Lupon Schmitt"
}

###
GET http://localhost:3000/api/wilder

###
PUT http://localhost:3000/api/wilder
Content-Type: application/json

{
	"id": "4",
	"name": "Lupon Truc"
}

###
DELETE http://localhost:3000/api/wilder
Content-Type: application/json

{
	"id": "2"
}
