POST http://localhost:3000/wilders
Content-Type: application/json

{
	"name": "Lupon true"
}

###
GET http://localhost:3000/wilders

###
PATCH http://localhost:3000/wilders/2
Content-Type: application/json

{
	"name": "Lupon Albert"
}

###
DELETE http://localhost:3000/wilders/3
Content-Type: application/json
