POST http://localhost:3000/wilders
Content-Type: application/json

{
	"name": "Lupon true"
}

###
GET http://localhost:3000/wilders

###
PATCH http://localhost:3000/wilders/8
Content-Type: application/json

{
	"name": "Albert"
}

###
DELETE http://localhost:3000/wilders/8
Content-Type: application/json
