POST http://localhost:5000/skills
Content-Type: application/json

{
	"name": "Test"
}

###
GET http://localhost:5000/skills


###
PATCH http://localhost:5000/skills/1
Content-Type: application/json

{
	"name": "Php"
}

###
DELETE http://localhost:5000/skills/4
Content-Type: application/json
